import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
import { handle } from './mlbfixture.mjs';
const require = createRequire(import.meta.url);
const { chromium } = require(execSync('npm root -g').toString().trim() + '/playwright');
const OUT = '/tmp/claude-0/shots'; execSync('mkdir -p ' + OUT);
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: +(process.env.W || 1200), height: 900 }, isMobile: !!process.env.MOBILE, hasTouch: !!process.env.MOBILE });
const page = await ctx.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + (e.stack || '').split('\n').slice(0, 4).join('\n')));
const offline = !!process.env.OFFLINE;
await page.route('https://statsapi.mlb.com/**', route => {
  if (offline) return route.abort();
  const j = handle(route.request().url());
  if (!j) return route.fulfill({ status: 404, body: '{}' });
  route.fulfill({ status: 200, contentType: 'application/json', headers: { 'access-control-allow-origin': '*' }, body: JSON.stringify(j) });
});
const shot = async n => { await page.screenshot({ path: `${OUT}/${n}.png` }); console.log('shot', n); };
const sfx = process.env.MOBILE ? '-m' : '';
await page.goto('http://127.0.0.1:8123/index.html#/live');
await page.waitForSelector('.games, .card.warn', { timeout: 60000 });
await page.evaluate(() => { location.hash = '#/live'; });
await shot('live-games' + sfx);
// go to a day with previews (after cutoff) 
await page.fill('input[type=date]', '2026-06-20'); await page.dispatchEvent('input[type=date]', 'change');
await page.waitForSelector('.gamecard');
await shot('live-preview' + sfx);
await page.click('.gamecard >> nth=0 >> text=Play it');
await page.waitForSelector('h2:has-text("set your lineups")'); await shot('live-lineup' + sfx); await page.click('text=Play ball'); await page.waitForSelector('.gv'); await page.click('text=Next batter'); await page.waitForTimeout(2600);
await shot('live-play' + sfx);
await page.click('text=Sim to end'); await page.waitForSelector('.final');
await page.click('text=Back to games'); await page.waitForSelector('.gamecard');
await page.click('text=Sim all'); await page.waitForTimeout(3000);
await shot('live-simmed' + sfx);
await page.click('button.tab:has-text("Standings")'); await shot('live-standings' + sfx);
await page.click('button.tab:has-text("Projection")'); await page.selectOption('select', '10'); await page.click('text=Run projection'); await page.waitForSelector('text=Projected finish', { timeout: 120000 });
await shot('live-proj' + sfx);
await page.click('button.tab:has-text("My sims")'); await shot('live-mine' + sfx);
console.log('ERRORS:', errors.length ? '\n' + errors.join('\n') : 'none');
await browser.close();
