import { handle, stats } from './mlbfixture.mjs';
import { setDataBase, loadGlobal, loadSeason, loadJSONGz } from '../web/js/data.js';
import { fetchLive, buildLiveSeason, buildLiveTeam, liveGameTeams, standingsFrom, projectSeason } from '../web/js/live.js';
import { Sim, mulberry32 } from '../web/js/engine.js';
console.log('fixture', stats);
globalThis.fetch = async (url) => { const j = handle(String(url)); return { ok: !!j, status: j ? 200 : 404, statusText: j ? 'OK' : 'nf', json: async () => j }; };
setDataBase(new URL('../data/', import.meta.url).pathname);
await loadGlobal();
const prior = await loadSeason(2025);
const idmap = await loadJSONGz(new URL('../data/idmap.json.gz', import.meta.url).pathname);
const live = await fetchLive(2026, m => {});
console.log('flags', live.flags, 'errors', live.errors, 'games', live.schedule.length, 'final', live.schedule.filter(g => g.state === 'Final').length);
const S = buildLiveSeason(live, prior, idmap);
console.log('players', S.players.length, 'bat rows', S.batRows.size, 'pit rows', S.pitRows.size, 'base', S.base.AL.bat.slice(0, 3).map(Math.round));
const nya = buildLiveTeam(S, 'NYA', live);
console.log(nya.name, nya.park, nya.lineup.map(x => x.pos + ':' + x.p.name).join(', '));
console.log('rot', nya.rotation.map(p => p.name).join(', '), '| pen', nya.bullpen.map(p => p.name + ':' + p.role).join(', '));
const g = live.schedule.find(x => x.state === 'Preview' && x.away === 'NYA');
const t = await liveGameTeams(S, live, g, { useFeed: false });
console.log('game', g.away, '@', g.home, 'SP', t.away.sp.name, 'vs', t.home.sp.name);
const rng = mulberry32(1); let runs = 0; const N = 300;
for (let i = 0; i < N; i++) { const r = new Sim(t.away, t.home, { rng, dh: true }).playGame(); runs += r.score[0] + r.score[1]; }
console.log('avg total runs', (runs / N).toFixed(2));
const rec = standingsFrom(live.schedule, S.teams);
console.log('sample record', rec.NYA.w, rec.NYA.l);
const meta = Object.fromEntries(Object.entries(S.teams).map(([c, t]) => [c, { name: t.n, lg: t.lg, div: t.d }]));
const t0 = Date.now();
const proj = await projectSeason(c => buildLiveTeam(S, c, live), meta, live.schedule, 3, () => {});
console.log('projection 3 sims', Date.now() - t0, 'ms', Object.entries(proj).sort((a, b) => b[1].w - a[1].w).slice(0, 4).map(([c, p]) => `${c} ${p.w.toFixed(1)} po ${p.po}`).join(' | '));
