import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
import { handle } from './mlbfixture.mjs';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(execSync('npm root -g').toString().trim() + '/playwright');
const OUT = '/tmp/claude-0/shots';
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.route('https://statsapi.mlb.com/**', route => { const j = handle(route.request().url()); route.fulfill({ status: j ? 200 : 404, contentType: 'application/json', headers: { 'access-control-allow-origin': '*' }, body: JSON.stringify(j || {}) }); });
const shot = async n => { await page.screenshot({ path: `${OUT}/m-${n}.png` }); console.log('shot', n); };
const base = 'http://127.0.0.1:8123/index.html';
await page.goto(base); await page.waitForSelector('.modes'); await shot('home');
console.log('overflow home', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth));
await page.goto(base + '#/game'); await page.waitForSelector('.gamelist tbody tr'); await shot('gamelist');
await page.click('.gamelist tbody tr >> nth=2'); await page.click('text=Play ball'); await page.waitForSelector('.gv'); await page.click('text=Next batter'); await page.waitForTimeout(1200); await shot('game');
console.log('overflow game', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth));
await page.evaluate(() => window.scrollTo(0, 900)); await shot('game-low');
await page.goto(base + '#/live'); await page.waitForSelector('.gamecard'); await shot('live');
console.log('overflow live', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth));
await page.goto(base + '#/season'); await page.waitForSelector('text=Start season'); await page.click('text=Start season'); await page.waitForSelector('.stand'); await shot('season');
console.log('overflow season', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth));
console.log('ERRORS', errors);
await browser.close();
